import React, { useState } from 'react';
import { Terminal, Copy, Check, ExternalLink, Code2, Server, Key, Shield } from 'lucide-react';

export const ApiDocumentation: React.FC = () => {
  const [copiedIndex, setCopiedIndex] = useState<number | null>(null);

  const handleCopy = (text: string, idx: number) => {
    navigator.clipboard.writeText(text);
    setCopiedIndex(idx);
    setTimeout(() => setCopiedIndex(null), 2000);
  };

  const endpoints = [
    {
      method: 'GET',
      path: '/api/serve/direct-link/:zoneId',
      badge: 'Public Ad-Serving',
      description:
        'Resolves and redirects direct smartlink clicks to the highest-bidding campaign matching visitor GEO and device, executing real-time anti-fraud heuristic scoring and platform commission settlement.',
      params: [
        { name: 'zoneId', in: 'path', type: 'string', desc: 'Publisher zone identifier (e.g. zone_4802)' },
        { name: 'format', in: 'query', type: 'string', desc: 'Optional "json" to receive metadata payload instead of 302 redirect' },
      ],
      responseSample: `{
  "status": 200,
  "campaignName": "Global Fintech & Trading Apps Tier-1",
  "destinationUrl": "https://offers.hilltopnetwork.com/click?offer_id=8910",
  "fraudScore": 12,
  "platformEarningsRecorded": 0.00075
}`,
    },
    {
      method: 'GET',
      path: '/api/serve/ad-tag/:zoneId.js',
      badge: 'Anti-AdBlock JS',
      description:
        'Delivers asynchronous, polymorphic anti-adblock ad tags for publishers to embed in website headers or footers.',
      params: [
        { name: 'zoneId', in: 'path', type: 'string', desc: 'Monetization zone ID' },
      ],
      responseSample: `// Dynamic polymorphic Anti-AdBlock loader
(function(){
  var script = document.createElement('script');
  script.async = true;
  script.src = "/api/serve/direct-link/zone_4801";
  document.head.appendChild(script);
})();`,
    },
    {
      method: 'POST',
      path: '/api/serve/conversion',
      badge: 'S2S Postback',
      description:
        'Affiliate network and tracker server-to-server (S2S) postback endpoint for logging CPA conversion attribution.',
      params: [
        { name: 'clickId', in: 'body', type: 'string', desc: 'Unique click identifier generated by HilltopAds' },
        { name: 'payout', in: 'body', type: 'number', desc: 'CPA commission payout amount in USD' },
      ],
      responseSample: `{
  "success": true,
  "message": "Conversion attributed to campaign camp_901"
}`,
    },
    {
      method: 'POST',
      path: '/api/campaigns',
      badge: 'Advertiser API',
      description: 'Creates a targeted advertiser campaign with budget caps, GEO targeting, and pricing bid.',
      params: [
        { name: 'name', in: 'body', type: 'string', desc: 'Campaign descriptive label' },
        { name: 'adFormat', in: 'body', type: 'string', desc: 'popunder | direct_link | in_page_push | banner' },
        { name: 'bid', in: 'body', type: 'number', desc: 'CPM or CPC bid rate in USD' },
        { name: 'targetGeos', in: 'body', type: 'array', desc: 'List of 2-letter ISO country codes or ["ALL"]' },
      ],
      responseSample: `{
  "success": true,
  "campaign": {
    "id": "camp_905",
    "name": "E-Commerce Mobile Smartlink",
    "status": "active",
    "bid": 2.50
  }
}`,
    },
    {
      method: 'POST',
      path: '/api/admin/verify-mfa',
      badge: 'Admin Security',
      description:
        'Authenticates admin credentials using multi-factor verification code, granting temporary session authorization.',
      params: [
        { name: 'code', in: 'body', type: 'string', desc: '6-digit TOTP authentication token' },
      ],
      responseSample: `{
  "success": true,
  "message": "MFA passed. Admin privileges granted."
}`,
    },
    {
      method: 'POST',
      path: '/api/admin/backups/create',
      badge: 'Disaster Recovery',
      description:
        'Generates an on-demand verified SHA256 cryptographic snapshot of the database state.',
      params: [],
      responseSample: `{
  "success": true,
  "backup": {
    "id": "bk_snapshot_1741220000",
    "filename": "backup_2026-09-05.json",
    "sizeBytes": 14592,
    "checksum": "c2084c6e9f2a..."
  }
}`,
    },
  ];

  return (
    <div className="py-12 bg-[#0B1120] text-slate-100 min-h-screen">
      <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 space-y-8">
        <div>
          <div className="flex items-center gap-2 text-xs font-semibold text-amber-400 mb-1">
            <Code2 className="w-4 h-4" />
            <span>Developer Documentation &amp; REST Specifications</span>
          </div>
          <h1 className="text-3xl font-extrabold text-white">HilltopAds Engine REST API v2.4</h1>
          <p className="text-slate-400 text-sm mt-2">
            Scalable, high-throughput programmatic endpoints for real-time ad serving, smartlinks, S2S conversion tracking,
            and administrative orchestration.
          </p>
        </div>

        {/* Quick architecture banner */}
        <div className="bg-slate-900/80 border border-slate-800 rounded-2xl p-5 flex flex-col md:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-amber-500/20 text-amber-400 flex items-center justify-center flex-shrink-0">
              <Server className="w-5 h-5" />
            </div>
            <div>
              <div className="text-xs font-bold text-white">Production High-Speed Microservice Node</div>
              <div className="text-[11px] text-slate-400">
                Sub-15ms response latency with in-memory heuristic anti-fraud filtering
              </div>
            </div>
          </div>
          <div className="flex items-center gap-2 font-mono text-xs text-emerald-400 bg-slate-950 px-3 py-1.5 rounded-lg border border-slate-800">
            <span className="w-2 h-2 rounded-full bg-emerald-400 animate-ping" />
            <span>STATUS: 100% OPERATIONAL</span>
          </div>
        </div>

        {/* Endpoints List */}
        <div className="space-y-6">
          {endpoints.map((ep, idx) => (
            <div
              key={ep.path}
              className="bg-slate-900/90 border border-slate-800 rounded-2xl overflow-hidden shadow-xl"
            >
              <div className="p-5 border-b border-slate-800 flex flex-col sm:flex-row sm:items-center justify-between gap-3">
                <div className="flex items-center gap-2.5">
                  <span
                    className={`px-2.5 py-1 rounded-md text-xs font-mono font-black ${
                      ep.method === 'GET'
                        ? 'bg-blue-500/20 text-blue-300 border border-blue-500/30'
                        : ep.method === 'POST'
                        ? 'bg-emerald-500/20 text-emerald-300 border border-emerald-500/30'
                        : 'bg-amber-500/20 text-amber-300 border border-amber-500/30'
                    }`}
                  >
                    {ep.method}
                  </span>
                  <code className="text-sm font-mono font-bold text-white">{ep.path}</code>
                </div>

                <span className="px-2.5 py-1 rounded-full text-[11px] font-semibold bg-slate-800 text-slate-300 border border-slate-700/60 self-start sm:self-auto">
                  {ep.badge}
                </span>
              </div>

              <div className="p-5 space-y-4 text-xs">
                <p className="text-slate-300 leading-relaxed">{ep.description}</p>

                {ep.params.length > 0 && (
                  <div>
                    <div className="text-[11px] font-bold uppercase tracking-wider text-slate-400 mb-2">
                      Parameters &amp; Payload
                    </div>
                    <div className="bg-slate-950 rounded-xl border border-slate-800 divide-y divide-slate-850 overflow-hidden">
                      {ep.params.map((p) => (
                        <div key={p.name} className="p-2.5 flex items-center justify-between gap-4">
                          <div className="flex items-center gap-2">
                            <code className="text-amber-300 font-bold">{p.name}</code>
                            <span className="text-[10px] text-slate-500 font-mono">({p.in})</span>
                            <span className="text-[10px] text-slate-400">[{p.type}]</span>
                          </div>
                          <div className="text-slate-400 text-right text-[11px]">{p.desc}</div>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                <div>
                  <div className="flex items-center justify-between mb-1.5">
                    <span className="text-[11px] font-bold uppercase tracking-wider text-slate-400">
                      Sample JSON Response
                    </span>
                    <button
                      onClick={() => handleCopy(ep.responseSample, idx)}
                      className="text-slate-400 hover:text-white text-[11px] flex items-center gap-1"
                    >
                      {copiedIndex === idx ? (
                        <>
                          <Check className="w-3 h-3 text-emerald-400" />
                          <span className="text-emerald-400">Copied</span>
                        </>
                      ) : (
                        <>
                          <Copy className="w-3 h-3" />
                          <span>Copy Sample</span>
                        </>
                      )}
                    </button>
                  </div>
                  <pre className="p-3.5 bg-slate-950 rounded-xl border border-slate-800 font-mono text-[11px] text-emerald-400 overflow-x-auto">
                    {ep.responseSample}
                  </pre>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};
